baseURL = 'https://jaxwang28.github.io/'
languageCode = 'en-us'
title = 'Jackson Blog'
theme = 'xmin'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 2
  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 3
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 4
  [[menus.main]]
    name = 'RSS'
    pageRef = '/rss'
    weight = 5
